server:
  tomcat:
    relaxed-query-chars: "[,]"
  port: 15557

spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/SafeDish?useSSL=false&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: 2635
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

token:
  secret-key: safedish-secret-key